name: Mealnote publish
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REACT_APP_BASE_URL: ${{secrets.REACT_APP_BASE_URL}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: InstallDependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: copy index.html to 404.html
        run: cp build/index.html build/404.html

      - name: publish Project
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./build
